# deploy kylin version: current only support Kylin 4
DEPLOY_KYLIN_VERSION: v4

# deploy platform: current only support ec2
DEPLOY_PLATFORM: ec2

AWS_REGION: cn-northwest-1                   # example: cn-northwest-1

# Note: this role must be created before run deployment
IAMRole: &IAM xxx

# Dangerous Params
ALWAYS_DESTROY_ALL: true                     # if set to false means that vpc for cluster always retain

# For Debug, null means that cluster on aws need to be created.
CLOUD_ADDR:

# example: s3://xxx/kylin
S3_FULL_BUCKET_PATH: &S3_FULL_PATH s3://xxx/kylin

# example: /xxx/kylin which matched above BucketFullPath suffix
S3_BUCKET_PATH: &S3_PATH /xxx/kylin

# Security key name must not be null
KeyName: &security_key xxxx

# Stack Names
# Note: if need to change stack names please change it in ../utils.py too.
VPC_STACK: ec2-or-emr-vpc-stack
DISTRIBUTION_STACK: ec2-distribution-stack
MASTER_STACK: ec2-master-stack
SLAVE_STACK: ec2-slave-stack

# Scale Nodes Nums, default num is 3.
# Scale Nodes Range is (from, to) which last node num contain the 'to'.
# Example: (4, 6) means that scale nodes will be [4, ,5, 6].
SCALE_NODES: (4, 6)

# Whether to use Local Cache + Soft Affinity
# Default is false.
# Note: this variable will be used in template which type is str!
USING_LOCALCACHE_SOFT_AFFINITY: &local_cache_soft_affinity "false"

#Backup Params
## backup meta file to S3 bucket, must not be null
BackupMetadataBucketFullPath:                 # example: s3://xxx/kylin/backup/

# Params
EC2_DISTRIBUTION_PARAMS:
  # None value can be passed by the pre-step output, so params need to wait pre-step complete.
  # Note: params details check in related yaml file
  PublicSubnetID:
  SecurityGroupID:
  EMREc2KeyName: *security_key
  AssociatedPublicIp: 'true'
  # Note: this bucket must be created before run
  BucketFullPath: *S3_FULL_PATH
  BucketPath: *S3_PATH

  DistributionScriptFileName: prepare-ec2-env-for-distribution.sh
  Ec2OperationRole: *IAM
  Ec2Mode: test
  # followed params is invalid if Ec2Mode(which set in the yaml) is 'test'
  Ec2InstanceTypeForDistribution: m5.2xlarge
  Ec2VolumeSizeForDistributionNode: '20'
  Ec2VolumnTypeForDistributionNode: gp2
EC2_MASTER_PARAMS:
  # None value can be passed by the pre-step output, so params need to wait pre-step complete.
  # Note: params details check in related yaml file
  Ec2DbHost:
  Ec2ZookeeperkHost:
  Ec2InstanceProfile:
  PublicSubnetID:
  SecurityGroupID:

  AssociatedPublicIp: 'true'
  # Must be in [ all, job, query ]
  Ec2KylinMode: all

  Ec2DbUser: 'root'
  Ec2DbPassword: '123456'
  # Note: this key pair must be created before run
  EMREc2KeyName: *security_key
  Ec2WaitingTime: '400'
  # Note: this bucket must be created before run
  BucketFullPath: *S3_FULL_PATH
  BucketPath:  *S3_PATH

  MasterScriptFileName: prepare-ec2-env-for-master.sh
  Ec2Mode: test
  # followed params is invalid if Ec2Mode(which set in the yaml) is 'test'
  InstanceType: m5.2xlarge
  Ec2VolumnTypeForMasterNode: gp2
  Ec2VolumeSizeForMasterNode: '50'
  LocalCacheSoftAffinity: *local_cache_soft_affinity

EC2_SLAVE_PARAMS:
  # None value can be passed by the pre-step output, so params need to wait pre-step complete.
  # Note: params details check in related yaml file
  MasterNodeHost:
  Ec2InstanceProfile:
  PublicSubnetID:
  SecurityGroupID:
  EMREc2KeyName: *security_key
  # set 'true' for test
  AssociatedPublicIp: 'true'
  WaitingTime: '400'
  # Note: this bucket must be created before run deployment
  BucketFullPath: *S3_FULL_PATH
  BucketPath: *S3_PATH
  SlaveScriptFileName: prepare-ec2-env-for-slave.sh
  Ec2Mode: test
  # followed params is invalid if Ec2Mode(which set in the yaml) is 'test'
  InstanceType: m5.2xlarge
  Ec2VolumnTypeForSlaveNode: gp2
  Ec2VolumeSizeForSlaveNode: '50'
  LocalCacheSoftAffinity: *local_cache_soft_affinity

EC2_SCALE_SLAVE_PARAMS:
  # None value can be passed by the pre-step output, so params need to wait pre-step complete.
  # Note: params details check in related yaml file
  MasterNodeHost:
  Ec2InstanceProfile:
  PublicSubnetID:
  SecurityGroupID:
  WorkerNum:
  WaitingTime: '100'
  EMREc2KeyName: *security_key
  # set 'true' for test
  AssociatedPublicIp: 'true'
  # Note: this bucket must be created before run raven
  BucketFullPath: *S3_FULL_PATH
  BucketPath: *S3_PATH
  ScriptFileName: prepare-ec2-env-for-slave.sh
  Ec2Mode: test
  # followed params is invalid if Ec2Mode(which set in the yaml) is 'test'
  InstanceType: m5.2xlarge
  Ec2VolumnTypeForSlaveNode: gp2
  Ec2VolumeSizeForSlaveNode: '50'
  LocalCacheSoftAffinity: *local_cache_soft_affinity
