AWSTemplateFormatVersion: 2010-09-09
Description: Create Cluster for ec2 instances and deploy related services, hadoop/spark/zookeeper/hive/jdk/kylin4
Parameters:
  # Must passed Parameters
  PublicSubnetID:
    Type: String
  SecurityGroupID:
    Type: String
  EMREc2KeyName:
    Type: String

#   Optional Parameters
  Ec2Mode:
    Type: String
    Default: test
    AllowedValues:
      - test
      - product
  AssociatedPublicIp:
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  BucketFullPath:
    Type: String
    Description: example s3://xxx/kylin
  BucketPath:
    Type: String
    Description: example /xxx/kylin which Url without prefix s3:/
  DistributionScriptFileName:
    Type: String
    Default: prepare-ec2-env-for-distribution.sh
  Ec2OperationRole:
    Type: String
    Description: Should be created by pre-step, must not be null !
  Ec2InstanceTypeForDistribution:
    Description: EC2 instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.2xlarge
    AllowedValues:
      - m5.2xlarge
      - m5.4xlarge
  Ec2InstanceTypeForDistributionForTest:
    Description: EC2 instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.xlarge
    AllowedValues:
      - m5.xlarge
  Ec2VolumeSizeForDistributionNode:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 30
  Ec2VolumnTypeForDistributionNode:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
      - sc1
      - st1
      - standard
  Ec2VolumeSizeForDistributionNodeForTest:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 20
  Ec2VolumnTypeForDistributionNodeForTest:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2

Mappings:
  AWSRegionArch2AMI:
    cn-north-1:
      HVMebs: ami-00ac27054b887ff5c
    cn-northwest-1:
      HVMebs: ami-0135cb179d33fbe3e

Conditions:
  NotNullSubnetID:
    !Not [!Equals [!Ref PublicSubnetID, ""]]
  NotNullEc2KeyName:
    !Not [!Equals [!Ref EMREc2KeyName, ""]]
  IsProductMode: !Equals [!Ref Ec2Mode, "product"]
  ValidConfigurationForEc2: !And
    - !Condition NotNullSubnetID
    - !Condition NotNullEc2KeyName
  IsAssociatedPublicIp: !Equals [!Ref AssociatedPublicIp, "true"]

Resources:
  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DeletionPolicy: Delete
    Properties:
      Roles:
        - !Ref Ec2OperationRole

  Ec2InstanceOfDistributionNode:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Condition: ValidConfigurationForEc2
    Properties:
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - HVMebs
      Tags:
        - Key: Project
          Value: Kylin4
        - Key: Name
          Value: Distribution Node
      InstanceType:
        !If
          - IsProductMode
          - !Ref Ec2InstanceTypeForDistribution
          - !Ref Ec2InstanceTypeForDistributionForTest
      IamInstanceProfile: !Ref Ec2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          Description: Auto create for Master node in benchmark
          AssociatePublicIpAddress: !Ref AssociatedPublicIp
          DeleteOnTermination: true
          SubnetId: !Ref PublicSubnetID
          GroupSet:
            - !Ref SecurityGroupID
      BlockDeviceMappings:
        - !If
          - IsProductMode
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForDistributionNode
              VolumeType: !Ref Ec2VolumnTypeForDistributionNode
              DeleteOnTermination: true
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForDistributionNodeForTest
              VolumeType: !Ref Ec2VolumnTypeForDistributionNodeForTest
              DeleteOnTermination: true
      KeyName: !Ref EMREc2KeyName
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -xe
              cd /home/ec2-user
              aws s3 cp ${PrivateBucketFullPath}/scripts/${PrivateDistributionScriptFileName} . --region ${PrivateRegion}
              bash ${PrivateDistributionScriptFileName} --bucket-url ${PrivateBucketPath} --region ${PrivateRegion}
              echo " Master is ready ..."
            - PrivateBucketFullPath: !Ref BucketFullPath
              PrivateDistributionScriptFileName: !Ref DistributionScriptFileName
              PrivateBucketPath: !Ref BucketPath
              PrivateRegion: !Ref AWS::Region

Outputs:
  # Env parameters
  PublicSubnetIDDependsOnDNode:
    Description: Public Subnet Id for distribution node
    Value: !Ref PublicSubnetID
  SecurityGroupIDDependsOnDNode:
    Description: Secrurity Group ID for distribution node
    Value: !Ref SecurityGroupID
  KeyPairNameDependsOnDNode:
    Description: KeyPair for distribution node
    Value: !Ref EMREc2KeyName
  InstanceProfileId:
    Description: Instance profile for cluster
    Value: !Ref Ec2InstanceProfile

  # Instance parameters
  Ec2InstanceIdOfDistributionNode:
    Description: the id of Distribution Node Innstance
    Value: !Ref Ec2InstanceOfDistributionNode
  DistributionNodePrivateIp:
    Description: Distribution Private IP
    Value: !GetAtt Ec2InstanceOfDistributionNode.PrivateIp
  DistributionNodePublicIp:
    Description: Distribution Public IP
    Value: !GetAtt Ec2InstanceOfDistributionNode.PublicIp
    Condition: IsAssociatedPublicIp
