AWSTemplateFormatVersion: 2010-09-09
Description: Create Kylin4 nodes for ec2 instances and deploy related services, hadoop/spark/zookeeper/hive/jdk/kylin4
Parameters:
  # Must passed Parameters
  Ec2DbIdentifier:
    Default: ec2-rds-kylin4
    Type: String

  Ec2DbUser:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: root
  Ec2DbPassword:
    NoEcho: 'true'
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: Must be created at pre-step and this can be modified in the script not yaml file.
  Ec2DbPort:
    Type: String
    Default: 3306
    AllowedValues:
      - 3306

  SecurityGroupId:
    Type: String
  SubnetGroupName:
    Type: String

  RDSEngine:
    Type: String
    Default: mysql
    AllowedValues:
      - mysql
  RDSEngineVersion:
    Type: String
    Default: 5.7.25

  Ec2Mode:
    Type: String
    Default: test
    AllowedValues:
      - test
      - product
    Description: set the flag for Mode, if not test use product's configuration

#   Optional Parameters
  EnableIAMAuthentication:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Zone:
    Type: String
    Default: cn-northwest-1b
    AllowedValues:
      - cn-northwest-1a
      - cn-northwest-1b
  DbName:
    Type: String
    Description: Initilize a db in rds
    Default: kylin
    AllowedValues:
      - kylin
  TypeOfRDS:
    Description: RDS instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.m5.xlarge
  VolumnTypeForRDS:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
  VolumeSizeForRDS:
    Type: Number
    Default: 10
    MinValue: 5
    MaxValue: 20

Conditions:
  NotNullSecurityGroupID: !Not [!Equals [!Ref SecurityGroupId, ""]]
  IsProductMode: !Equals [!Ref Ec2Mode, "product"]

Resources:
  Ec2RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Condition: NotNullSecurityGroupID
    Properties:
      Tags:
        - Key: Project
          Value: Kylin4
        - Key: Name
          Value: RDS for kylin4
      AllocatedStorage: !Ref VolumeSizeForRDS
      AvailabilityZone: !Ref Zone
      DBSubnetGroupName: !Ref SubnetGroupName
      # The number of days for which automated backups are retained. Setting this parameter to a positive number enables backups.
      # Setting this parameter to 0 disables automated backups.
      BackupRetentionPeriod: 0
      DBInstanceClass: !Ref TypeOfRDS
      DBInstanceIdentifier: !Ref Ec2DbIdentifier
      DBName: !Ref DbName
      VPCSecurityGroups:
        - !Ref SecurityGroupId
      EnableIAMDatabaseAuthentication: !Ref EnableIAMAuthentication
      Engine: !Ref RDSEngine
      EngineVersion: !Ref RDSEngineVersion
      MasterUsername: !Ref Ec2DbUser
      MasterUserPassword: !Ref Ec2DbPassword
      Port: !Ref Ec2DbPort
      StorageType: !Ref VolumnTypeForRDS

Outputs:
  DbHost:
    Description: Db Endpoints Host
    Value: !GetAtt Ec2RDSInstance.Endpoint.Address
  DbPort:
    Description: Db Endpoints Port
    Value: !GetAtt Ec2RDSInstance.Endpoint.Port

