from enum import Enum


class Config(Enum):
    # DEBUG params
    CLOUD_ADDR = 'CLOUD_ADDR'

    # Other params
    AWS_REGION = 'AWS_REGION'
    KYLIN_SCALE_NODES = 'KYLIN_SCALE_NODES'
    SPARK_WORKER_SCALE_NODES = 'SPARK_WORKER_SCALE_NODES'
    KYLIN_MODE = 'KYLIN_MODE'

    # Deploy params
    DEPLOY_PLATFORM = 'DEPLOY_PLATFORM'

    # Stack Names
    VPC_STACK = 'VPC_STACK'
    RDS_STACK = 'RDS_STACK'
    STATIC_SERVICE_STACK = 'STATIC_SERVICE_STACK'
    ZOOKEEPERS_STACK = 'ZOOKEEPERS_STACK'
    KYLIN_STACK = 'KYLIN_STACK'
    SPARK_MASTER_STACK = 'SPARK_MASTER_STACK'
    SPARK_WORKER_STACK = 'SPARK_WORKER_STACK'

    # Params
    EC2_STATIC_SERVICES_PARAMS = 'EC2_STATIC_SERVICES_PARAMS'
    EC2_KYLIN4_PARAMS = 'EC2_KYLIN4_PARAMS'
    EC2_KYLIN4_SCALE_PARAMS = 'EC2_KYLIN4_SCALE_PARAMS'
    EC2_VPC_PARAMS = 'EC2_VPC_PARAMS'
    EC2_RDS_PARAMS = 'EC2_RDS_PARAMS'
    EC2_ZOOKEEPERS_PARAMS = 'EC2_ZOOKEEPERS_PARAMS'
    EC2_SPARK_MASTER_PARAMS = 'EC2_SPARK_MASTER_PARAMS'
    EC2_SPARK_WORKER_PARAMS = 'EC2_SPARK_WORKER_PARAMS'
    EC2_SPARK_SCALE_SLAVE_PARAMS = 'EC2_SPARK_SCALE_SLAVE_PARAMS'

    # RDS Params
    DB_IDENTIFIER = 'DB_IDENTIFIER'
    DB_HOST = 'DB_HOST'
    DB_PORT = 'DB_PORT'
    DB_USER = 'DB_USER'
    DB_PASSWORD = 'DB_PASSWORD'
